# Generated by Django 6.0.3 on 2026-05-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0002_user_blocked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='info',
        ),
    ]
